// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzydwkmhslafzguiezxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6eWR3a21oc2xhZnpndWllenhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NjM5NjEsImV4cCI6MjA2NzAzOTk2MX0.9_h6NNa3ryQFcRt7nZmLOQFHfH2JqLylyRdUwnhqjNk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});